sudo: required
dist: xenial

env:
    - CODECOV_TOKEN="3978605c-c3c9-423b-b814-172a262c958b"

language: c

compiler:
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

script:
    - make CFLAGS="-DSITL -ftest-coverage"
    - make CFLAGS="-ftest-coverage"
    - make CFLAGS="-DCSS_READY -ftest-coverage"
    - make spotless
after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
